### ISSUE TITLE
Dissect feature puts the images into document root

### ISSUE THREAD

**Issue by eLtMosen** [beroset/asteroid-hosttools#1]
It would be convenient if the script would make a directory `<watch-image>-dissect/` and place them there.
This would help in case more than one watches are being worked on.

**Comment by beroset** [comment]
I handle this another way.  I create the subdirectory, say, `catfish-dissect` manually, `cd` into it and then invoke `watch-image <path-to-image>`.

**Comment by eLtMosen** [comment]
Ok, thanks for reminding me of basic linux things, eheh.
